local pseudojson = {}

weapons = {}
weapons[1] = {
    name = "Gauss Canon",
    rarity = 1,
    proj = true,
    beam = false,
    homing = false,
    fireQty = 1,
    fireSpread = 0,
    fireCooldown = 0,
    fireDelay = 0,
    cooldown = 1,
    speed = 100,
    rangeMin = 0,
    rangeMax = 2000,
    energy = 1,
    dmgShield = 5,
    dmgHull = 0
}
weapons[2] = {
    name = "Gatling Gun",
    rarity = 1,
    proj = true,
    beam = false,
    homing = false,
    fireQty = 10,
    fireSpread = 0,
    fireCooldown = 0.1,
    fireDelay = 1,
    cooldown = 3,
    speed = 300,
    rangeMin = 0,
    rangeMax = 2000,
    energy = 1,
    dmgShield = 1,
    dmgHull = 1
}
weapons[3] = {
    name = "Laser Canon",
    rarity = 1,
    proj = true,
    beam = false,
    homing = false,
    fireQty = 1,
    fireSpread = 0,
    fireCooldown = 0,
    fireDelay = 0,
    cooldown = 0.5,
    speed = 400,
    rangeMin = 0,
    rangeMax = 2000,
    energy = 1,
    dmgShield = 1,
    dmgHull = 0
}
weapons[4] = {
    name = "Torpedo",
    rarity = 1,
    proj = true,
    beam = false,
    homing = false,
    fireQty = 1,
    fireSpread = 0,
    fireCooldown = 0,
    fireDelay = 0,
    cooldown = 2,
    speed = 200,
    rangeMin = 0,
    rangeMax = 2000,
    energy = 1,
    dmgShield = 5,
    dmgHull = 1
}
weapons[5] = {
    name = "Plasma Gun",
    rarity = 1,
    proj = true,
    beam = false,
    homing = false,
    fireQty = 3,
    fireSpread = 0,
    fireCooldown = 0.25,
    fireDelay = 0,
    cooldown = 2,
    speed = 1,
    rangeMin = 0,
    rangeMax = 2000,
    energy = 1,
    dmgShield = 1,
    dmgHull = 1
}
weapons[6] = {
    name = "Nova Gun",
    rarity = 1,
    proj = true,
    beam = false,
    homing = false,
    fireQty = 16,
    fireSpread = 360,
    fireCooldown = 0.017,
    fireDelay = 0,
    cooldown = 2,
    speed = 100,
    rangeMin = 0,
    rangeMax = 2000,
    energy = 1,
    dmgShield = 1,
    dmgHull = 1
}

return pseudojson